"""add ogle_target to candidate

Revision ID: 0c9b033b2ae7
Revises: cc3149c9667b
Create Date: 2021-03-25 15:01:35.853652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c9b033b2ae7'
down_revision = 'cc3149c9667b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('ogle_target', sa.String(length=128)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'ogle_target')
    # ### end Alembic commands ###
