"""pspl_gp_fit started and finished to candidate_level4

Revision ID: 143214893923
Revises: 5db18b3b07bb
Create Date: 2021-05-07 14:47:06.544290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '143214893923'
down_revision = '5db18b3b07bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('pspl_gp_fit_datetime_finished', sa.DateTime(), nullable=True))
    op.add_column('candidate_level4', sa.Column('pspl_gp_fit_datetime_started', sa.DateTime(), nullable=True))
    op.add_column('candidate_level4', sa.Column('pspl_gp_fit_finished', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('candidate_level4', sa.Column('pspl_gp_fit_started', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'pspl_gp_fit_datetime_finished')
    op.drop_column('candidate_level4', 'pspl_gp_fit_datetime_started')
    op.drop_column('candidate_level4', 'pspl_gp_fit_finished')
    op.drop_column('candidate_level4', 'pspl_gp_fit_started')
    # ### end Alembic commands ###
