"""empty message

Revision ID: 1435d0497691
Revises: 
Create Date: 2020-11-13 18:13:03.481368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1435d0497691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    op.create_index(op.f('ix_puzle_user_email'), 'user', ['email'], unique=True, schema='puzle')
    op.create_index(op.f('ix_puzle_user_username'), 'user', ['username'], unique=True, schema='puzle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puzle_user_username'), table_name='user', schema='puzle')
    op.drop_index(op.f('ix_puzle_user_email'), table_name='user', schema='puzle')
    op.drop_table('user', schema='puzle')
    # ### end Alembic commands ###
