"""eta_thresholds_low

Revision ID: 1b32c4beb213
Revises: 21c5f07f107f
Create Date: 2021-03-23 17:05:09.528449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON

# revision identifiers, used by Alembic.
revision = '1b32c4beb213'
down_revision = '21c5f07f107f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_process_job', sa.Column('eta_thresholds_high', JSON))
    op.alter_column('star_process_job', column_name='eta_thresholds', new_column_name='eta_thresholds_low')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('star_process_job', column_name='eta_thresholds_low', new_column_name='eta_thresholds')
    op.drop_column('star_process_job', 'eta_thresholds_high')
    # ### end Alembic commands ###
