"""add q3c to candidate

Revision ID: 1d8cb9add574
Revises: 0c9b033b2ae7
Create Date: 2021-03-25 15:50:31.514734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d8cb9add574'
down_revision = '0c9b033b2ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE INDEX ON puzle.candidate (q3c_ang2ipix(ra, dec));')
    op.execute('CLUSTER candidate_q3c_ang2ipix_idx ON puzle.candidate;')
    op.execute('ANALYZE puzle.candidate;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX candidate_q3c_ang2ipix_idx;')
    # ### end Alembic commands ###
