"""convert star ids to strs

Revision ID: 1dcde1491056
Revises: d9e677eb2453
Create Date: 2021-01-07 18:56:50.001016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcde1491056'
down_revision = 'd9e677eb2453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('star', 'source_ids')
    op.add_column('star', sa.Column('source_ids', sa.ARRAY(sa.String(length=128)), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('star', 'source_ids')
    op.add_column('star', sa.Column('source_ids', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###
