"""add t0_complete / level5 to level4

Revision ID: 204c7bc5264d
Revises: 59025c3ab7fe
Create Date: 2021-05-18 08:15:04.411580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '204c7bc5264d'
down_revision = '59025c3ab7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('t0_complete', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('candidate_level4', sa.Column('level5', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 't0_complete')
    op.drop_column('candidate_level4', 'level5')
    # ### end Alembic commands ###
