"""add in_source to object table

Revision ID: 206f65b2b504
Revises: 8c67f94b52b0
Create Date: 2020-11-24 16:30:50.950733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206f65b2b504'
down_revision = '8c67f94b52b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('in_source', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'in_source')
    # ### end Alembic commands ###
