"""rename num_sources to num_stars_pass_n_days

Revision ID: 20ab7bbabaf7
Revises: 7d4ec8851b09
Create Date: 2021-04-02 07:30:22.138787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20ab7bbabaf7'
down_revision = '7d4ec8851b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('star_process_job', column_name='num_sources', new_column_name='num_stars_pass_n_days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('star_process_job', column_name='num_stars_pass_n_days', new_column_name='num_sources')
    # ### end Alembic commands ###
