"""add num_candidates to star_process_job

Revision ID: 21c5f07f107f
Revises: 7008a366eebd
Create Date: 2021-03-22 18:27:10.936595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21c5f07f107f'
down_revision = '7008a366eebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_process_job', sa.Column('num_candidates', sa.Integer, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('star_process_job', 'num_candidates')
    # ### end Alembic commands ###
