"""add num_obs_pass_n_days to source_process_job

Revision ID: 2290c6780444
Revises: 76dc7ced2ff1
Create Date: 2021-03-18 14:46:17.819542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2290c6780444'
down_revision = '76dc7ced2ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', column_name='eta_threshold', new_column_name='eta_threshold_best')
    op.add_column('star_process_job', sa.Column('num_objs_pass_n_days', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', column_name='eta_threshold_best', new_column_name='eta_threshold')
    op.drop_column('star_process_job', 'num_objs_pass_n_days')
    # ### end Alembic commands ###
