"""add priority column to star_process_job

Revision ID: 26570fa16077
Revises: cd4f50737568
Create Date: 2021-03-05 15:09:30.281595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26570fa16077'
down_revision = 'cd4f50737568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_process_job', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('star_process_job', 'priority')
    # ### end Alembic commands ###
