"""remove chi2_dof

Revision ID: 28ea137623cb
Revises: 9f618ab6833a
Create Date: 2021-05-06 10:42:22.027086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28ea137623cb'
down_revision = '9f618ab6833a'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_column('candidate_level3', 'chi_squared_dof_best')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level3', sa.Column('chi_squared_dof_best', sa.Integer))
    # ### end Alembic commands ###
