"""star_ingest_job table

Revision ID: 2d76d6f52970
Revises: df95d5cf7ab1
Create Date: 2021-01-07 14:47:13.228903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d76d6f52970'
down_revision = 'df95d5cf7ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star_ingest_job',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('started', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('finished', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('datetime_started', sa.DateTime(), nullable=True),
    sa.Column('datetime_finished', sa.DateTime(), nullable=True),
    sa.Column('slurm_job_id', sa.Integer(), nullable=True),
    sa.Column('source_ingest_job_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    op.create_index(op.f('ix_puzle_source_ingest_job_id'), 'source', ['ingest_job_id'], unique=False, schema='puzle')
    op.create_index(op.f('ix_puzle_star_ingest_job_id'), 'star', ['ingest_job_id'], unique=False, schema='puzle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('star_ingest_job', schema='puzle')
    op.drop_index(op.f('ix_puzle_source_ingest_job_id'), table_name='source',
                  schema='puzle')
    op.drop_index(op.f('ix_puzle_star_ingest_job_id'), table_name='star',
                  schema='puzle')
    # ### end Alembic commands ###
