"""slurm_job_rank column

Revision ID: 3273e180fac8
Revises: f27c75d06ed3
Create Date: 2021-01-11 10:38:58.712446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3273e180fac8'
down_revision = 'f27c75d06ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_ingest_job', sa.Column('slurm_job_rank', sa.Integer(), nullable=True))
    op.add_column('source_ingest_job', sa.Column('slurm_job_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('star_ingest_job', 'slurm_job_rank')
    op.drop_column('source_ingest_job', 'slurm_job_rank')
    # ### end Alembic commands ###
