"""add ztf_ids to source table

Revision ID: 3709cab5abf4
Revises: 8dea6dd71726
Create Date: 2020-11-16 19:09:57.872327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3709cab5abf4'
down_revision = '8dea6dd71726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('_ztf_ids', sa.String(length=256),
                                      nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', '_ztf_ids')
    # ### end Alembic commands ###
