"""rename candidate table to level 2

Revision ID: 3a10f6392770
Revises: 20ab7bbabaf7
Create Date: 2021-04-20 07:06:15.329777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a10f6392770'
down_revision = '20ab7bbabaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('candidate', 'candidate_level2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('candidate_level2', 'candidate')
    # ### end Alembic commands ###
