"""init ps1_psc table

Revision ID: 3cd723e4e53d
Revises: 3273e180fac8
Create Date: 2021-03-01 10:52:26.482709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd723e4e53d'
down_revision = '3273e180fac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps1_psc',
                    sa.Column('obj_id', sa.BigInteger(), nullable=False),
                    sa.Column('ra_stack', sa.Float(), nullable=False),
                    sa.Column('dec_stack', sa.Float(), nullable=False),
                    sa.Column('rf_score', sa.Float(), nullable=False),
                    sa.Column('quality_flag', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('obj_id')
    )
    op.execute('CREATE INDEX ON ps1_psc (q3c_ang2ipix(ra_stack, dec_stack));')
    op.execute('CLUSTER ps1_psc_q3c_ang2ipix_idx ON ps1_psc;')
    op.execute('ANALYZE ps1_psc;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX ps1_psc_q3c_ang2ipix_idx;')
    op.drop_table('ps1_psc')
    # ### end Alembic commands ###
