"""add fit columns to candidate

Revision ID: 3db8bc81f654
Revises: 694949d49f4f
Create Date: 2021-03-11 14:42:07.750244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3db8bc81f654'
down_revision = '694949d49f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', column_name='source_ids', new_column_name='source_id_arr')
    op.alter_column('candidate', column_name='filter_ids', new_column_name='filter_id_arr')
    op.drop_column('candidate', 'etas')
    op.drop_column('candidate', 'rf_scores')
    op.drop_column('candidate', 'eta_residuals')
    op.drop_column('candidate', 'eta_thresholds')
    op.add_column('candidate', sa.Column('eta_best', sa.Float))
    op.add_column('candidate', sa.Column('rf_score_best', sa.Float))
    op.add_column('candidate', sa.Column('eta_residual_best', sa.Float))
    op.add_column('candidate', sa.Column('eta_threshold', sa.Float))
    op.add_column('candidate', sa.Column('t_E_best', sa.Float))
    op.add_column('candidate', sa.Column('t_0_best', sa.Float))
    op.add_column('candidate', sa.Column('f_0_best', sa.Float))
    op.add_column('candidate', sa.Column('f_1_best', sa.Float))
    op.add_column('candidate', sa.Column('a_type_best', sa.String(length=256)))
    op.add_column('candidate', sa.Column('chi_squared_flat_best', sa.Float))
    op.add_column('candidate', sa.Column('chi_squared_delta_best', sa.Float))
    op.add_column('candidate', sa.Column('idx_best', sa.Integer))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', column_name='source_id_arr', new_column_name='source_ids')
    op.alter_column('candidate', column_name='filter_id_arr', new_column_name='filter_ids')
    op.add_column('candidate', sa.Column('etas', sa.ARRAY(sa.Float)))
    op.add_column('candidate', sa.Column('rf_scores', sa.ARRAY(sa.Float)))
    op.add_column('candidate', sa.Column('eta_residuals', sa.ARRAY(sa.Float)))
    op.add_column('candidate', sa.Column('eta_thresholds', sa.ARRAY(sa.Float)))
    op.drop_column('candidate', 'eta_best')
    op.drop_column('candidate', 'rf_score_best')
    op.drop_column('candidate', 'eta_residual_best')
    op.drop_column('candidate', 'eta_threshold')
    op.drop_column('candidate', 't_E_best')
    op.drop_column('candidate', 't_0_best')
    op.drop_column('candidate', 'f_0_best')
    op.drop_column('candidate', 'f_1_best')
    op.drop_column('candidate', 'a_type_best')
    op.drop_column('candidate', 'chi_squared_flat_best')
    op.drop_column('candidate', 'chi_squared_delta_best')
    op.drop_column('candidate', 'idx_best')
    # ### end Alembic commands ###
