"""add fit columns to candidate

Revision ID: 3db8bc81f654
Revises: 694949d49f4f
Create Date: 2021-03-11 14:42:07.750244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3db8bc81f654'
down_revision = '694949d49f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', column_name='source_ids', new_column_name='source_id_arr')
    op.alter_column('candidate', column_name='filter_ids', new_column_name='filter_id_arr')
    op.alter_column('candidate', column_name='etas', new_column_name='eta_arr')
    op.alter_column('candidate', column_name='rf_scores', new_column_name='rf_score_arr')
    op.alter_column('candidate', column_name='eta_residuals', new_column_name='eta_residual_arr')
    op.alter_column('candidate', column_name='eta_thresholds', new_column_name='eta_threshold_arr')
    op.add_column('candidate', sa.Column('t_E_arr', sa.ARRAY(sa.Float), nullable=False))
    op.add_column('candidate', sa.Column('t_0_arr', sa.ARRAY(sa.Float), nullable=False))
    op.add_column('candidate', sa.Column('f_0_arr', sa.ARRAY(sa.Float), nullable=False))
    op.add_column('candidate', sa.Column('f_1_arr', sa.ARRAY(sa.Float), nullable=False))
    op.add_column('candidate', sa.Column('a_type_arr', sa.ARRAY(sa.String(length=256)), nullable=False))
    op.add_column('candidate', sa.Column('chi_squared_flat_arr', sa.ARRAY(sa.Float), nullable=False))
    op.add_column('candidate', sa.Column('chi_squared_delta_arr', sa.ARRAY(sa.Float), nullable=False))
    op.add_column('candidate', sa.Column('idx_best', sa.Integer, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', column_name='source_id_arr', new_column_name='source_ids')
    op.alter_column('candidate', column_name='filter_id_arr', new_column_name='filter_ids')
    op.alter_column('candidate', column_name='eta_arr', new_column_name='etas')
    op.alter_column('candidate', column_name='rf_score_arr', new_column_name='rf_scores')
    op.alter_column('candidate', column_name='eta_residual_arr', new_column_name='eta_residuals')
    op.alter_column('candidate', column_name='eta_threshold_arr', new_column_name='eta_thresholds')
    op.drop_column('candidate', 't_E_arr')
    op.drop_column('candidate', 't_0_arr')
    op.drop_column('candidate', 'f_0_arr')
    op.drop_column('candidate', 'f_1_arr')
    op.drop_column('candidate', 'a_type_arr')
    op.drop_column('candidate', 'chi_squared_flat_arr')
    op.drop_column('candidate', 'chi_squared_delta_arr')
    op.drop_column('candidate', 'idx_best')
    # ### end Alembic commands ###
