"""chi2 columns in candidate_level4;


Revision ID: 444442c0556f
Revises: 9a9abca6fb1b
Create Date: 2021-05-06 17:50:34.269516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '444442c0556f'
down_revision = '9a9abca6fb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'chi_squared_ulens_inside_arr')
    op.drop_column('candidate_level4', 'num_epochs_inside_arr')
    op.add_column('candidate_level4', sa.Column('num_days_inside_arr', sa.ARRAY(sa.Integer)))
    op.add_column('candidate_level4', sa.Column('num_days_outside_arr', sa.ARRAY(sa.Integer)))
    op.add_column('candidate_level4', sa.Column('chi_squared_flat_inside_arr', sa.ARRAY(sa.Float)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('chi_squared_ulens_inside_arr', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('num_epochs_inside_arr', sa.ARRAY(sa.Integer)))
    op.drop_column('candidate_level4', 'num_days_inside_arr')
    op.drop_column('candidate_level4', 'num_days_outside_arr')
    op.drop_column('candidate_level4', 'chi_squared_flat_inside_arr')
    # ### end Alembic commands ###
