"""delete object table

Revision ID: 474b38fa27dd
Revises: b10eb29eb314
Create Date: 2020-12-09 16:13:08.380003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474b38fa27dd'
down_revision = 'b10eb29eb314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_object_id_g_fkey', 'source', schema='puzle', type_='foreignkey')
    op.drop_constraint('source_object_id_r_fkey', 'source', schema='puzle', type_='foreignkey')
    op.drop_constraint('source_object_id_i_fkey', 'source', schema='puzle', type_='foreignkey')
    op.drop_table('object', schema='puzle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('nepochs', sa.Integer(), nullable=False),
    sa.Column('filterid', sa.Integer(), nullable=False),
    sa.Column('fieldid', sa.Integer(), nullable=False),
    sa.Column('rcid', sa.Integer(), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('lightcurve_position', sa.BigInteger(), nullable=False),
    sa.Column('lightcurve_filename', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    op.create_index(op.f('ix_puzle_object_filterid'), 'object', ['filterid'], unique=False, schema='puzle')
    op.create_index(op.f('ix_puzle_object_lightcurve_filename'), 'object', ['lightcurve_filename'], unique=False, schema='puzle')
    op.create_foreign_key('source_object_id_g_fkey', 'source', 'object', ['object_id_g'], ['id'], source_schema='puzle', referent_schema='puzle')
    op.create_foreign_key('source_object_id_r_fkey', 'source', 'object', ['object_id_r'], ['id'], source_schema='puzle', referent_schema='puzle')
    op.create_foreign_key('source_object_id_i_fkey', 'source', 'object', ['object_id_i'], ['id'], source_schema='puzle', referent_schema='puzle')
    # ### end Alembic commands ###
