"""pspl_gp columns to candidate_level4


Revision ID: 48fc470e0e04
Revises: bfd245280b98
Create Date: 2021-05-17 07:44:43.592960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48fc470e0e04'
down_revision = 'bfd245280b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('chi2_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('rchi2_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('logL_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('t0_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('t0_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('u0_amp_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('u0_amp_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('tE_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('tE_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('piE_E_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('piE_E_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('piE_N_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('piE_N_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('b_sff_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('b_sff_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('mag_base_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('mag_base_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('gp_log_sigma_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('gp_log_sigma_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('gp_rho_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('gp_rho_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('gp_log_omega04_S0_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('gp_log_omega04_S0_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('gp_log_omega0_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('gp_log_omega0_err_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('b_sff_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('b_sff_err_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('mag_base_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('mag_base_err_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('gp_log_sigma_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('gp_log_sigma_err_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('gp_rho_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('gp_rho_err_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('gp_log_omega04_S0_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('gp_log_omega04_S0_err_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('gp_log_omega0_arr_pspl_gp', sa.ARRAY(sa.Float)))
    op.add_column('candidate_level4', sa.Column('gp_log_omega0_err_arr_pspl_gp', sa.ARRAY(sa.Float)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'chi2_pspl_gp')
    op.drop_column('candidate_level4', 'rchi2_pspl_gp')
    op.drop_column('candidate_level4', 'logL_pspl_gp')
    op.drop_column('candidate_level4', 't0_pspl_gp')
    op.drop_column('candidate_level4', 't0_err_pspl_gp')
    op.drop_column('candidate_level4', 'u0_amp_pspl_gp')
    op.drop_column('candidate_level4', 'u0_amp_err_pspl_gp')
    op.drop_column('candidate_level4', 'tE_pspl_gp')
    op.drop_column('candidate_level4', 'tE_err_pspl_gp')
    op.drop_column('candidate_level4', 'piE_E_pspl_gp')
    op.drop_column('candidate_level4', 'piE_E_err_pspl_gp')
    op.drop_column('candidate_level4', 'piE_N_pspl_gp')
    op.drop_column('candidate_level4', 'piE_N_err_pspl_gp')
    op.drop_column('candidate_level4', 'b_sff_pspl_gp')
    op.drop_column('candidate_level4', 'b_sff_err_pspl_gp')
    op.drop_column('candidate_level4', 'mag_base_pspl_gp')
    op.drop_column('candidate_level4', 'mag_base_err_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_sigma_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_sigma_err_pspl_gp')
    op.drop_column('candidate_level4', 'gp_rho_pspl_gp')
    op.drop_column('candidate_level4', 'gp_rho_err_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_omega04_S0_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_omega04_S0_err_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_omega0_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_omega0_err_pspl_gp')
    op.drop_column('candidate_level4', 'b_sff_arr_pspl_gp')
    op.drop_column('candidate_level4', 'b_sff_err_arr_pspl_gp')
    op.drop_column('candidate_level4', 'mag_base_arr_pspl_gp')
    op.drop_column('candidate_level4', 'mag_base_err_arr_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_sigma_arr_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_sigma_err_arr_pspl_gp')
    op.drop_column('candidate_level4', 'gp_rho_arr_pspl_gp')
    op.drop_column('candidate_level4', 'gp_rho_err_arr_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_omega04_S0_arr_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_omega04_S0_err_arr_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_omega0_arr_pspl_gp')
    op.drop_column('candidate_level4', 'gp_log_omega0_err_arr_pspl_gp')