"""drop node for slurm_job_id

Revision ID: 5274a69a183e
Revises: 9ebe25c3e66b
Create Date: 2020-11-17 14:39:08.312084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5274a69a183e'
down_revision = '9ebe25c3e66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_ingest_job', sa.Column('slurm_job_id', sa.Integer(), nullable=True))
    op.drop_column('source_ingest_job', 'node')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_ingest_job', sa.Column('node', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('source_ingest_job', 'slurm_job_id')
    # ### end Alembic commands ###
