"""category to candidate_level4`


Revision ID: 59025c3ab7fe
Revises: ce702d9a2a2d
Create Date: 2021-05-17 18:33:43.456525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59025c3ab7fe'
down_revision = 'ce702d9a2a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('category', sa.String(length=128)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'category')
    # ### end Alembic commands ###
