"""remove foreign key constraints

Revision ID: 591f588386e9
Revises: 474b38fa27dd
Create Date: 2020-12-22 13:30:53.088646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591f588386e9'
down_revision = '474b38fa27dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_ingest_job')
    op.create_table('source_ingest_job',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ra_start', sa.Float(), nullable=False),
    sa.Column('ra_end', sa.Float(), nullable=False),
    sa.Column('dec_start', sa.Float(), nullable=False),
    sa.Column('dec_end', sa.Float(), nullable=False),
    sa.Column('started', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('finished', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('datetime_started', sa.DateTime(), nullable=True),
    sa.Column('datetime_finished', sa.DateTime(), nullable=True),
    sa.Column('slurm_job_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_ingest_job', schema='puzle')
    # ### end Alembic commands ###
