"""sigma_peaks outside

Revision ID: 59ea69e7128d
Revises: a4b1fea46950
Create Date: 2021-04-30 11:23:07.902986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59ea69e7128d'
down_revision = 'a4b1fea46950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level3', sa.Column('num_3sigma_peaks_outside_2tE_best', sa.Float))
    op.add_column('candidate_level3', sa.Column('num_5sigma_peaks_outside_2tE_best', sa.Float))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level3', 'num_3sigma_peaks_outside_2tE_best')
    op.drop_column('candidate_level3', 'num_5sigma_peaks_outside_2tE_best')
    # ### end Alembic commands ###

