"""delta_hmjd_outside_arr to candidate_level4

Revision ID: 5db18b3b07bb
Revises: 444442c0556f
Create Date: 2021-05-07 06:52:56.067545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5db18b3b07bb'
down_revision = '444442c0556f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('delta_hmjd_outside_arr', sa.ARRAY(sa.Float)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'delta_hmjd_outside_arr')
    # ### end Alembic commands ###
