"""add num_epochs_edges to job stats

Revision ID: 656bbce9289a
Revises: 2290c6780444
Create Date: 2021-03-22 13:09:35.676080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON

# revision identifiers, used by Alembic.
revision = '656bbce9289a'
down_revision = '2290c6780444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_process_job', sa.Column('num_epochs_edges', JSON))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('star_process_job', 'num_epochs_edges')
    # ### end Alembic commands ###
