"""add fit columns to sources

Revision ID: 6b0505db9fbe
Revises: 3db8bc81f654
Create Date: 2021-03-11 16:19:36.058198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b0505db9fbe'
down_revision = '3db8bc81f654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('fit_filter', sa.String(length=128)))
    op.add_column('source', sa.Column('fit_t_0', sa.Float))
    op.add_column('source', sa.Column('fit_t_E', sa.Float))
    op.add_column('source', sa.Column('fit_f_0', sa.Float))
    op.add_column('source', sa.Column('fit_f_1', sa.Float))
    op.add_column('source', sa.Column('fit_a_type', sa.String(length=128)))
    op.add_column('source', sa.Column('fit_chi_squared_delta', sa.Float))
    op.add_column('source', sa.Column('fit_chi_squared_flat', sa.Float))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'fit_filter')
    op.drop_column('source', 'fit_t_0')
    op.drop_column('source', 'fit_t_E')
    op.drop_column('source', 'fit_f_0')
    op.drop_column('source', 'fit_f_1')
    op.drop_column('source', 'fit_a_type')
    op.drop_column('source', 'fit_chi_squared_delta')
    op.drop_column('source', 'fit_chi_squared_flat')
    # ### end Alembic commands ###
