"""add q3c radial query to source

Revision ID: 6d831aeb37a1
Revises: 5274a69a183e
Create Date: 2020-11-19 18:11:45.813496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d831aeb37a1'
down_revision = '5274a69a183e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE INDEX ON puzle.source (q3c_ang2ipix(ra, dec));')
    op.execute('CLUSTER source_q3c_ang2ipix_idx ON puzle.source;')
    op.execute('ANALYZE puzle.source;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX source_q3c_ang2ipix_idx;')
    # ### end Alembic commands ###
