"""correct epoch_edges and eta_thresholds columns

Revision ID: 7008a366eebd
Revises: 656bbce9289a
Create Date: 2021-03-22 18:05:39.925019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON

# revision identifiers, used by Alembic.
revision = '7008a366eebd'
down_revision = '656bbce9289a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_process_job', sa.Column('eta_thresholds', JSON))
    op.alter_column('star_process_job', column_name='num_epochs_edges', new_column_name='epoch_edges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('star_process_job', column_name='epoch_edges', new_column_name='num_epochs_edges')
    op.drop_column('star_process_job', 'eta_thresholds')
    # ### end Alembic commands ###
