"""delta_hmjd_outside_pspl_gp to candidate_level4

Revision ID: 7035453a2482
Revises: 204c7bc5264d
Create Date: 2021-05-18 20:20:29.208765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7035453a2482'
down_revision = '204c7bc5264d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('delta_hmjd_outside_pspl_gp', sa.Float))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'delta_hmjd_outside_pspl_gp')
    # ### end Alembic commands ###
