"""add candidate stats columns

Revision ID: 7b162d32f76b
Revises: f538493e8a98
Create Date: 2021-03-04 14:38:14.907861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b162d32f76b'
down_revision = 'f538493e8a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('filter_ids', sa.ARRAY(sa.Integer), nullable=False))
    op.add_column('candidate', sa.Column('etas', sa.ARRAY(sa.Float), nullable=False))
    op.add_column('candidate', sa.Column('rf_scores', sa.ARRAY(sa.Float), nullable=False))
    op.add_column('candidate', sa.Column('eta_residuals', sa.ARRAY(sa.Float), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'filter_ids')
    op.drop_column('candidate', 'etas')
    op.drop_column('candidate', 'rf_scores')
    op.drop_column('candidate', 'eta_residuals')
    # ### end Alembic commands ###
