"""add cand_id column to source

Revision ID: 7d4ec8851b09
Revises: 1d8cb9add574
Create Date: 2021-03-25 16:33:13.711193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d4ec8851b09'
down_revision = '1d8cb9add574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('cand_id', sa.String(length=128)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'cand_id')
    # ### end Alembic commands ###