"""add ingest_job_id to source

Revision ID: 7df8564a73ce
Revises: e23fcef90f10
Create Date: 2020-12-24 14:46:50.296825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df8564a73ce'
down_revision = 'e23fcef90f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('ingest_job_id', sa.BigInteger(), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'ingest_job_id')
    # ### end Alembic commands ###
