"""add stats columns to star ingest job

Revision ID: 8650af858372
Revises: d71fa8725958
Create Date: 2021-03-04 13:55:35.410407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8650af858372'
down_revision = 'd71fa8725958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_process_job', sa.Column('num_stars', sa.Integer, nullable=True))
    op.add_column('star_process_job', sa.Column('num_sources', sa.Integer, nullable=True))
    op.add_column('star_process_job', sa.Column('num_objs', sa.Integer, nullable=True))
    op.add_column('star_process_job', sa.Column('num_objs_pass_eta', sa.Integer, nullable=True))
    op.add_column('star_process_job', sa.Column('num_stars_pass_eta', sa.Integer, nullable=True))
    op.add_column('star_process_job', sa.Column('num_objs_pass_rf', sa.Integer, nullable=True))
    op.add_column('star_process_job', sa.Column('num_stars_pass_rf', sa.Integer, nullable=True))
    op.add_column('star_process_job', sa.Column('num_objs_pass_eta_residual', sa.Integer, nullable=True))
    op.add_column('star_process_job', sa.Column('num_stars_pass_eta_residual', sa.Integer, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('star_process_job', 'num_stars')
    op.drop_column('star_process_job', 'num_sources')
    op.drop_column('star_process_job', 'num_objs')
    op.drop_column('star_process_job', 'num_objs_pass_eta')
    op.drop_column('star_process_job', 'num_stars_pass_eta')
    op.drop_column('star_process_job', 'num_objs_pass_rf')
    op.drop_column('star_process_job', 'num_stars_pass_rf')
    op.drop_column('star_process_job', 'num_objs_pass_eta_residual')
    op.drop_column('star_process_job', 'num_stars_pass_eta_residual')
    # ### end Alembic commands ###
