"""delta_hmjd_outside for multiple tE

Revision ID: 886707b48867
Revises: 28ea137623cb
Create Date: 2021-05-06 10:49:22.747467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '886707b48867'
down_revision = '28ea137623cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_level3', column_name='num_epochs_inside_1tE_best', new_column_name='num_days_inside_1tE_best')
    op.alter_column('candidate_level3', column_name='num_epochs_inside_2tE_best', new_column_name='num_days_inside_2tE_best')
    op.alter_column('candidate_level3', column_name='num_epochs_inside_3tE_best', new_column_name='num_days_inside_3tE_best')
    op.alter_column('candidate_level3', column_name='delta_hmjd_outside_best', new_column_name='delta_hmjd_outside_1tE_best')
    op.add_column('candidate_level3', sa.Column('delta_hmjd_outside_2tE_best', sa.Float))
    op.add_column('candidate_level3', sa.Column('delta_hmjd_outside_3tE_best', sa.Float))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_level3', column_name='num_days_inside_1tE_best', new_column_name='num_epochs_inside_1tE_best')
    op.alter_column('candidate_level3', column_name='num_days_inside_2tE_best', new_column_name='num_epochs_inside_2tE_best')
    op.alter_column('candidate_level3', column_name='num_days_inside_3tE_best', new_column_name='num_epochs_inside_3tE_best')
    op.alter_column('candidate_level3', column_name='delta_hmjd_outside_1tE_best', new_column_name='delta_hmjd_outside_best')
    op.drop_column('candidate_level3', 'delta_hmjd_outside_2tE_best')
    op.drop_column('candidate_level3', 'delta_hmjd_outside_3tE_best')
    # ### end Alembic commands ###
