"""init user object source tables

Revision ID: 92ace37d31dd
Revises: 
Create Date: 2020-11-15 21:58:05.788923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ace37d31dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('nepochs', sa.Integer(), nullable=False),
    sa.Column('filterid', sa.Integer(), nullable=False),
    sa.Column('fieldid', sa.Integer(), nullable=False),
    sa.Column('rcid', sa.Integer(), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('lightcurve_position', sa.BigInteger(), nullable=False),
    sa.Column('lightcurve_filename', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    op.create_index(op.f('ix_puzle_object_filterid'), 'object', ['filterid'], unique=False, schema='puzle')
    op.create_index(op.f('ix_puzle_object_lightcurve_filename'), 'object', ['lightcurve_filename'], unique=False, schema='puzle')
    op.create_table('source',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('object_id_g', sa.BigInteger(), nullable=True),
    sa.Column('object_id_r', sa.BigInteger(), nullable=True),
    sa.Column('object_id_i', sa.BigInteger(), nullable=True),
    sa.Column('lightcurve_position_g', sa.BigInteger(), nullable=True),
    sa.Column('lightcurve_position_r', sa.BigInteger(), nullable=True),
    sa.Column('lightcurve_position_i', sa.BigInteger(), nullable=True),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('lightcurve_filename', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    op.create_index(op.f('ix_puzle_source_lightcurve_filename'), 'source', ['lightcurve_filename'], unique=False, schema='puzle')
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    op.create_index(op.f('ix_puzle_user_email'), 'user', ['email'], unique=True, schema='puzle')
    op.create_index(op.f('ix_puzle_user_username'), 'user', ['username'], unique=True, schema='puzle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puzle_user_username'), table_name='user', schema='puzle')
    op.drop_index(op.f('ix_puzle_user_email'), table_name='user', schema='puzle')
    op.drop_table('user', schema='puzle')
    op.drop_index(op.f('ix_puzle_source_lightcurve_filename'), table_name='source', schema='puzle')
    op.drop_table('source', schema='puzle')
    op.drop_index(op.f('ix_puzle_object_lightcurve_filename'), table_name='object', schema='puzle')
    op.drop_index(op.f('ix_puzle_object_filterid'), table_name='object', schema='puzle')
    op.drop_table('object', schema='puzle')
    # ### end Alembic commands ###
