"""num_days_outside to candidate_level3

Revision ID: 9a9abca6fb1b
Revises: e8812d2ed953
Create Date: 2021-05-06 15:38:08.919426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a9abca6fb1b'
down_revision = 'e8812d2ed953'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('candidate_level3', sa.Column('num_days_outside_1tE_best', sa.Integer))
    op.add_column('candidate_level3', sa.Column('num_days_outside_2tE_best', sa.Integer))
    op.add_column('candidate_level3', sa.Column('num_days_outside_3tE_best', sa.Integer))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level3', 'num_days_outside_1tE_best')
    op.drop_column('candidate_level3', 'num_days_outside_2tE_best')
    op.drop_column('candidate_level3', 'num_days_outside_3tE_best')
    # ### end Alembic commands ###