"""init sourceIngestJob table

Revision ID: 9ebe25c3e66b
Revises: 3709cab5abf4
Create Date: 2020-11-17 13:57:25.290397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebe25c3e66b'
down_revision = '3709cab5abf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_ingest_job',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lightcurve_filename', sa.String(length=128), nullable=False),
    sa.Column('process_rank', sa.Integer(), nullable=False),
    sa.Column('process_size', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('node', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    op.create_index(op.f('ix_puzle_source_ingest_job_lightcurve_filename'), 'source_ingest_job', ['lightcurve_filename'], unique=False, schema='puzle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puzle_source_ingest_job_lightcurve_filename'), table_name='source_ingest_job', schema='puzle')
    op.drop_table('source_ingest_job', schema='puzle')
    # ### end Alembic commands ###
