"""ammend chi_squared on candidate_level3

Revision ID: 9f618ab6833a
Revises: e889f1c19b6d
Create Date: 2021-05-06 09:38:55.475963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f618ab6833a'
down_revision = 'e889f1c19b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_level3', column_name='chi_squared_inside_1tE_best', new_column_name='chi_squared_flat_inside_1tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_inside_2tE_best', new_column_name='chi_squared_flat_inside_2tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_inside_3tE_best', new_column_name='chi_squared_flat_inside_3tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_outside_1tE_best', new_column_name='chi_squared_flat_outside_1tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_outside_2tE_best', new_column_name='chi_squared_flat_outside_2tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_outside_3tE_best', new_column_name='chi_squared_flat_outside_3tE_best')
    op.add_column('candidate_level3', sa.Column('delta_hmjd_outside_best', sa.Float))
    op.add_column('candidate_level3', sa.Column('chi_squared_dof_best', sa.Integer))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_level3', column_name='chi_squared_flat_inside_1tE_best', new_column_name='chi_squared_inside_1tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_flat_inside_2tE_best', new_column_name='chi_squared_inside_2tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_flat_inside_3tE_best', new_column_name='chi_squared_inside_3tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_flat_outside_1tE_best', new_column_name='chi_squared_outside_1tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_flat_outside_2tE_best', new_column_name='chi_squared_outside_2tE_best')
    op.alter_column('candidate_level3', column_name='chi_squared_flat_outside_3tE_best', new_column_name='chi_squared_outside_3tE_best')
    op.drop_column('candidate_level3', 'delta_hmjd_outside_best')
    op.drop_column('candidate_level3', 'chi_squared_dof_best')
    # ### end Alembic commands ###
