"""num_5sigma_peaks_inside_2tE_best

Revision ID: a4b1fea46950
Revises: 36f216fd6828
Create Date: 2021-04-30 08:22:03.344909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4b1fea46950'
down_revision = '36f216fd6828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level3', sa.Column('num_3sigma_peaks_inside_2tE_best', sa.Float))
    op.add_column('candidate_level3', sa.Column('num_5sigma_peaks_inside_2tE_best', sa.Float))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level3', 'num_3sigma_peaks_inside_2tE_best')
    op.drop_column('candidate_level3', 'num_5sigma_peaks_inside_2tE_best')
    # ### end Alembic commands ###
