"""ongoing flag to candidate_level5

Revision ID: a9b5cb83337a
Revises: 7035453a2482
Create Date: 2021-06-04 09:35:00.339971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9b5cb83337a'
down_revision = '7035453a2482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('ongoing', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'ongoing')
    # ### end Alembic commands ###