"""add foreign keys to objects

Revision ID: aa192fe06ac3
Revises: 92ace37d31dd
Create Date: 2020-11-16 10:04:47.438065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa192fe06ac3'
down_revision = '92ace37d31dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'source', 'object', ['object_id_g'], ['id'], source_schema='puzle', referent_schema='puzle')
    op.create_foreign_key(None, 'source', 'object', ['object_id_r'], ['id'], source_schema='puzle', referent_schema='puzle')
    op.create_foreign_key(None, 'source', 'object', ['object_id_i'], ['id'], source_schema='puzle', referent_schema='puzle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', schema='puzle', type_='foreignkey')
    op.drop_constraint(None, 'source', schema='puzle', type_='foreignkey')
    op.drop_constraint(None, 'source', schema='puzle', type_='foreignkey')
    # ### end Alembic commands ###
