"""piE to candidate_level4

Revision ID: aab440b29489
Revises: 48fc470e0e04
Create Date: 2021-05-17 08:12:55.489953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aab440b29489'
down_revision = '48fc470e0e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('piE_pspl_gp', sa.Float))
    op.add_column('candidate_level4', sa.Column('piE_err_pspl_gp', sa.Float))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'piE_pspl_gp')
    op.drop_column('candidate_level4', 'piE_err_pspl_gp')
    # ### end Alembic commands ###
