"""add uploaded column to ingest jobs

Revision ID: b349850a4fde
Revises: 2d76d6f52970
Create Date: 2021-01-07 16:36:46.626861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b349850a4fde'
down_revision = '2d76d6f52970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_ingest_job', sa.Column('uploaded', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('star_ingest_job', sa.Column('uploaded', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_ingest_job', 'uploaded')
    op.drop_column('star_ingest_job', 'uploaded')
    # ### end Alembic commands ###
