"""num_pspl_gp_fit_lightcurves to candidate_level4

Revision ID: bfd245280b98
Revises: 960bfc8030f9
Create Date: 2021-05-11 07:41:02.951132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfd245280b98'
down_revision = '960bfc8030f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('num_pspl_gp_fit_lightcurves', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'num_pspl_gp_fit_lightcurves')
    # ### end Alembic commands ###

