"""source_id_arr and color_arr to pspl_gp in candidate_level4

Revision ID: ce702d9a2a2d
Revises: aab440b29489
Create Date: 2021-05-17 08:48:16.998366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce702d9a2a2d'
down_revision = 'aab440b29489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level4', sa.Column('source_id_arr_pspl_gp', sa.ARRAY(sa.String(length=128))))
    op.add_column('candidate_level4', sa.Column('color_arr_pspl_gp', sa.ARRAY(sa.String(length=8))))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level4', 'source_id_arr_pspl_gp')
    op.drop_column('candidate_level4', 'color_arr_pspl_gp')
    # ### end Alembic commands ###
