"""init star_process_job_table

Revision ID: d43b502feeb3
Revises: 3cd723e4e53d
Create Date: 2021-03-03 16:38:44.228556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd43b502feeb3'
down_revision = '3cd723e4e53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star_process_job',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('started', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('finished', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('uploaded', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('datetime_started', sa.DateTime(), nullable=True),
    sa.Column('datetime_finished', sa.DateTime(), nullable=True),
    sa.Column('slurm_job_id', sa.Integer(), nullable=True),
    sa.Column('slurm_job_rank', sa.Integer(), nullable=True),
    sa.Column('source_ingest_job_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('star_process_job', schema='puzle')
    # ### end Alembic commands ###
