"""change star id column from int to str

Revision ID: d71fa8725958
Revises: d43b502feeb3
Create Date: 2021-03-04 10:22:31.923214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd71fa8725958'
down_revision = 'd43b502feeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_star_association_star_id_fkey', 'user_star_association', schema='puzle')
    op.drop_column('user_star_association', 'star_id')
    op.drop_constraint('star_pkey', 'star', schema='puzle')
    op.drop_column('star', 'id')
    op.add_column('star', sa.Column('id', sa.String(length=128), nullable=False))
    op.create_primary_key('star_pkey', 'star', ['id'])
    op.add_column('user_star_association', sa.Column('star_id', sa.String(length=128), nullable=False))
    op.create_foreign_key('user_star_association_star_id_fkey',
                          'user_star_association',
                          'star', ['star_id'], ['id'],
                          source_schema='puzle', referent_schema='puzle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_star_association_star_id_fkey', 'user_star_association', schema='puzle')
    op.drop_column('user_star_association', 'star_id')
    op.drop_constraint('star_pkey', 'star', schema='puzle')
    op.drop_column('star', 'id')
    op.add_column('star', sa.Column('id', sa.BigInteger, nullable=False))
    op.create_primary_key('star_pkey', 'star', ['id'])
    op.add_column('user_star_association', sa.Column('star_id', sa.BigInteger, nullable=False))
    op.create_foreign_key('user_star_association_star_id_fkey',
                          'user_star_association',
                          'star', ['star_id'], ['id'],
                          source_schema='puzle', referent_schema='puzle')
    # ### end Alembic commands ###