"""source manual id column

Revision ID: d9e677eb2453
Revises: b349850a4fde
Create Date: 2021-01-07 17:29:22.577399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e677eb2453'
down_revision = 'b349850a4fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('id_str', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'id_str')
    # ### end Alembic commands ###
