"""create candidate level_3 table

Revision ID: e104b276c1de
Revises: 3a10f6392770
Create Date: 2021-04-20 07:31:51.854939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e104b276c1de'
down_revision = '3a10f6392770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_level3',
                    sa.Column('id', sa.String(length=128), nullable=False),
                    sa.Column('ra', sa.Float(), nullable=False),
                    sa.Column('dec', sa.Float(), nullable=False),
                    sa.Column('source_id_arr', sa.ARRAY(sa.String(length=128)), nullable=False),
                    sa.Column('color_arr', sa.ARRAY(sa.String(length=8)), nullable=False),
                    sa.Column('pass_arr', sa.ARRAY(sa.Boolean), nullable=False),
                    sa.Column('idx_best', sa.Integer, nullable=False),
                    sa.Column('num_objs_pass', sa.Integer, nullable=False),
                    sa.Column('num_objs_tot', sa.Integer, nullable=False),
                    sa.Column('eta_best', sa.Float(), nullable=True),
                    sa.Column('eta_residual_best', sa.Float(), nullable=True),
                    sa.Column('t0_best', sa.Float(), nullable=True),
                    sa.Column('u0_amp_best', sa.Float(), nullable=True),
                    sa.Column('tE_best', sa.Float(), nullable=True),
                    sa.Column('mag_src_best', sa.Float(), nullable=True),
                    sa.Column('b_sff_best', sa.Float(), nullable=True),
                    sa.Column('piE_E_best', sa.Float(), nullable=True),
                    sa.Column('piE_N_best', sa.Float(), nullable=True),
                    sa.Column('chi_squared_delta_best', sa.Float(), nullable=True),
                    sa.Column('comments', sa.String(length=1024), nullable=True),
                    sa.Column('_ztf_ids', sa.String(length=256), nullable=True),
                    sa.Column('ogle_target', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='puzle'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_level3', schema='puzle')
    # ### end Alembic commands ###
