"""init star table

Revision ID: e23fcef90f10
Revises: 591f588386e9
Create Date: 2020-12-23 11:40:31.684707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23fcef90f10'
down_revision = '591f588386e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('_ztf_ids', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
    )
    op.create_table('user_star_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('star_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['star_id'], ['puzle.star.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['puzle.user.id'], ),
    schema='puzle'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_star_association', schema='puzle')
    op.drop_table('star', schema='puzle')
    # ### end Alembic commands ###
