"""add num_epochs and num_days to candidate_level3

Revision ID: e25031a7b360
Revises: e104b276c1de
Create Date: 2021-04-22 11:51:42.138054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e25031a7b360'
down_revision = 'e104b276c1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_level3', sa.Column('num_epochs_best', sa.Integer()))
    op.add_column('candidate_level3', sa.Column('num_days_best', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_level3', 'num_epochs_best')
    op.drop_column('candidate_level3', 'num_days_best')
    # ### end Alembic commands ###
