"""chi_squared_delta_best to chi_squared_ulens_best

Revision ID: e8812d2ed953
Revises: 886707b48867
Create Date: 2021-05-06 11:22:21.446840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8812d2ed953'
down_revision = '886707b48867'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('candidate_level3', column_name='chi_squared_delta_best',
                    new_column_name='chi_squared_ulens_best')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_level3', column_name='chi_squared_ulens_best',
                    new_column_name='chi_squared_delta_best')
    # ### end Alembic commands ###
