"""candidate_level4

Revision ID: e889f1c19b6d
Revises: 59ea69e7128d
Create Date: 2021-05-02 13:45:04.067257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e889f1c19b6d'
down_revision = '59ea69e7128d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_level4',
                    sa.Column('id', sa.String(length=128), nullable=False),
                    sa.Column('ra', sa.Float(), nullable=False),
                    sa.Column('dec', sa.Float(), nullable=False),
                    sa.Column('source_id_arr', sa.ARRAY(sa.String(length=128)), nullable=False),
                    sa.Column('color_arr', sa.ARRAY(sa.String(length=8)), nullable=False),
                    sa.Column('pass_arr', sa.ARRAY(sa.Boolean), nullable=False),
                    sa.Column('idx_best', sa.Integer, nullable=False),
                    sa.Column('num_objs_pass', sa.Integer, nullable=False),
                    sa.Column('num_objs_tot', sa.Integer, nullable=False),
                    sa.Column('num_epochs_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('num_days_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('eta_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('eta_residual_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('t0_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('u0_amp_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('tE_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('mag_src_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('b_sff_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('piE_E_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('piE_N_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('chi_squared_ulens_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('chi_squared_flat_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('chi_squared_ulens_inside_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('chi_squared_flat_outside_arr', sa.ARRAY(sa.Float), nullable=True),
                    sa.Column('num_epochs_inside_arr', sa.ARRAY(sa.Integer), nullable=True),
                    sa.Column('num_3sigma_peaks_inside_arr', sa.ARRAY(sa.Integer), nullable=True),
                    sa.Column('num_3sigma_peaks_outside_arr', sa.ARRAY(sa.Integer), nullable=True),
                    sa.Column('num_5sigma_peaks_inside_arr', sa.ARRAY(sa.Integer), nullable=True),
                    sa.Column('num_5sigma_peaks_outside_arr', sa.ARRAY(sa.Integer), nullable=True),
                    sa.Column('comments', sa.String(length=1024), nullable=True),
                    sa.Column('_ztf_ids', sa.String(length=256), nullable=True),
                    sa.Column('ogle_target', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='puzle'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_level4', schema='puzle')
    # ### end Alembic commands ###

