"""add pass_arr to candidate

Revision ID: eadd87d54a48
Revises: 935e1058a4b7
Create Date: 2021-03-23 18:29:30.322379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eadd87d54a48'
down_revision = '935e1058a4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('pass_arr', sa.ARRAY(sa.Boolean)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'pass_arr')
    # ### end Alembic commands ###
