"""eta_threshold low and high in candidate

Revision ID: f1060d175a12
Revises: 1b32c4beb213
Create Date: 2021-03-23 17:12:18.539045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1060d175a12'
down_revision = '1b32c4beb213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('eta_threshold_high_best', sa.Float))
    op.alter_column('candidate', column_name='eta_threshold_best', new_column_name='eta_threshold_low_best')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', column_name='eta_threshold_low_best', new_column_name='eta_threshold_best')
    op.drop_column('candidate', 'eta_threshold_high_best')
    # ### end Alembic commands ###
