"""switch_source_primary_key_to_id_str

Revision ID: f27c75d06ed3
Revises: 1dcde1491056
Create Date: 2021-01-07 19:51:01.928408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27c75d06ed3'
down_revision = '1dcde1491056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_source_association')

    op.drop_constraint('source_pkey', 'source', schema='puzle', type_='primary')
    op.drop_column('source', 'id')
    op.alter_column('source', column_name='id_str', new_column_name='id')
    op.create_primary_key('source_pkey', 'source', ['id'])

    op.create_table('user_source_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['puzle.source.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['puzle.user.id'], ),
    schema='puzle'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
