"""change source ingest job ended to finished

Revision ID: f2fdfe3eaae0
Revises: 6d831aeb37a1
Create Date: 2020-11-19 18:54:28.657671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fdfe3eaae0'
down_revision = '6d831aeb37a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_ingest_job', sa.Column('finished', sa.Boolean(), server_default='f', nullable=False))
    op.drop_column('source_ingest_job', 'ended')
    op.drop_column('source_ingest_job', 'started')
    op.add_column('source_ingest_job', sa.Column('started', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_ingest_job', sa.Column('ended', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('source_ingest_job', 'finished')
    op.drop_column('source_ingest_job', 'started')
    op.add_column('source_ingest_job', sa.Column('started', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###
