"""add candidate table

Revision ID: f538493e8a98
Revises: 8650af858372
Create Date: 2021-03-04 14:09:33.363151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f538493e8a98'
down_revision = '8650af858372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('source_ids', sa.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('ingest_job_id', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('_ztf_ids', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='puzle'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate', schema='puzle')
    # ### end Alembic commands ###
